### ISSUE TITLE
[Bug]: Build error while upgrading to 0.9.x

### ISSUE THREAD

**Issue by nromptea42** [braze-inc/braze-react-native-sdk#255]
### Which Platforms?

iOS

### Which React Native Version?

0.73.6

### Which @braze/react-native-sdk SDK version?

0.9.1

### Repro Rate

100%

### Steps To Reproduce

While upgrading to Braze `0.9.1` from Braze `0.8.4` i'm getting a build error on iOS.

### Expected Behavior

The build should have worked.

### Actual Incorrect Behavior

It gave me these errors on xcode

```
Undefined symbol: _$s11ActivityKit0A0C23pushToStartTokenUpdatesAC04PushfG0Vyx_GvgZ
Linker command failed with exit code 1 (use -v to see invocation)
```

And this one when building with `react-native run-ios`

```
⚠️  ld: Could not find or use auto-linked framework '_BrazeAssetsClient'
⚠️  ld: Could not find or use auto-linked framework 'BrazeArchitecture'
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes'
⚠️  ld: Could not find or use auto-linked framework 'BrazeComposableArchitecture'
⚠️  ld: Could not find or use auto-linked framework 'NanoCombine'
⚠️  ld: Could not find or use auto-linked framework '_BrazeUtils'
⚠️  ld: Could not find or use auto-linked framework 'BrazeCasePaths'
⚠️  ld: Could not find or use auto-linked framework '_BrazeUnzipClient'
⚠️  ld: Could not find or use auto-linked framework 'NanoCombineExt'

❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Additional Information

- I have hermes enabled
- I'm not using react-native new architecture
- It's working fine on version `0.8.4`

Maybe I missed an update on the documentation, if it's case i'm sorry and could you point me to it ?

**Comment by jerielng** [comment]
Hi @nromptea42, version `9.0.0` of our React Native SDK implicitly links to version `8.1.0` of our native Swift SDK. Starting in the `8.x.x` series, we bumped minimum support to Xcode 15.2, per the [changelog](https://github.com/braze-inc/braze-swift-sdk/compare/7.5.0...8.1.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) in the Swift SDK.

You will need to either use Xcode 15.2+, or use a version of this SDK lower than `9.0.0`.

**Comment by nromptea42** [comment]
Oh right I used Xcode 15.0, thanks a lot for the help 🙏
