### ISSUE TITLE
[Bug]: ITMS-91056: Invalid privacy manifest, ITMS-91064: Invalid tracking information

### ISSUE THREAD

**Issue by QSuraj** [braze-inc/braze-react-native-sdk#280]
### Which Platforms?

iOS

### Which React Native Version?

0.69.12

### Which @braze/react-native-sdk SDK version?

8.4.0

### Repro Rate

100% of the time

### Steps To Reproduce

Example:
  1. `import Braze from "@braze/react-native-sdk"`.
  2. `Braze.changeUser("id")`
  2. Run the app.

<img width="699" alt="387571371-05c11dfa-a2f6-42a0-ba6b-f1ea98871c51" src="https://github.com/user-attachments/assets/7231b8b1-b2a8-4396-9227-84458d330282">

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<true/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeCoarseLocation</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<true/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeProductPersonalization</string>
				<string>NSPrivacyCollectedDataTypePurposeAnalytics</string>
			</array>
		</dict>
	</array>
	<key>NSPrivacyTrackingDomains</key>
	<array>
		<string>sdk-tracking.iad-05.braze.com</string>
	</array>
</dict>
</plist>
```

### Expected Behavior

There should be no error while uploding to App Store.

### Actual Incorrect Behavior

Gets following error after uploading to App store -
<img width="707" alt="387570243-3fe824e2-d072-4dfc-a0ba-e58aad27f972" src="https://github.com/user-attachments/assets/4a3f1961-8a8a-44b3-a722-83fc99ee33b8">

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “BrazeLocation.bundle/PrivacyInfo.xcprivacy”. Keys and values in your app’s privacy manifests must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “BrazeKit.bundle/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn’t empty. Keys and values in your app’s privacy manifests must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

### Additional Information

Reponening - https://github.com/braze-inc/braze-react-native-sdk/issues/279

**Comment by QSuraj** [comment]
Was suggested to update to 10.0.0 - https://github.com/braze-inc/braze-react-native-sdk/issues/279#issuecomment-2485847640

Getting following error when I try to update and do a pod install as we are working on React Native 0.69.12.
braze-react-native-sdk [9.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/9.0.0) and above needs react-native 71+. 

```
Invalid `braze-react-native-sdk.podspec` file: undefined method `install_modules_dependencies' for module Pod.
```

**Comment by QSuraj** [comment]
@jerielng Can we release a patch for 8.4.0, may be 8.5.0? With fixes in [10.0.0](https://github.com/braze-inc/braze-swift-sdk/compare/8.4.0...9.0.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)

**Comment by jerielng** [comment]
Hey @QSuraj, our React Native SDK requires a minimum of `0.71`+ as a way to keep in line with the official React Native [matrix of support](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md). If you are facing difficulties upgrading, could you reach out to support@braze.com? Thanks!

**Comment by QSuraj** [comment]
@jerielng Thank you for pointing this out.

While I’m not opposed to updating, the issue arises after upgrading, as braze-react-native-sdk library now requires a minimum React Native version of 0.71+. Unfortunately, we are unable to update our project to this React Native version, as it is a large-scale project, and migrating just to support this SDK would be a significant effort.

Could you consider addressing the issue in version 8.4.0 of the react-native-braze-sdk to ensure compatibility with older React Native versions? Many large projects may face similar challenges with upgrading due to dependency constraints. Ideally, libraries should maintain backward compatibility to accommodate such use cases.

The above error message is thrown because of defining the privacy.xcPrivacy incorrectly. Just fixing that would fix the issue on 8.4.0.

**Comment by jerielng** [comment]
@QSuraj Thanks for sharing the additional context! Unfortunately, the jump from `8.4.0` to `10.0.0` involves breaking changes that span two major versions, particularly with the updates to our underlying Swift SDK bindings, which go from `7.7.0` to  `9.0.0` and are scoped specifically to the corresponding version of the React Native SDK, so it would not be an isolated fix that is being targeted here. I previously mentioned redirecting to support since they could explore potential alternative solutions here. Let us know if that would work for you!

**Comment by hokstuff** [comment]
I'm closing out this ticket since we have forwarded the client to our Support channels for more catered investigation and recommendations. Thanks!
